
COMPLETION_DEFAULT_TEMPERATURE = 0.5
COMPLETION_DEFAULT_MAX_TOKENS = 500

CODE_DEFAULT_TEMPERATURE = 0.8
CODE_DEFAULT_MAX_TOKENS = 4000

EDIT_DEFAULT_TEMPERATURE = 0.7

CHAT_DEFAULT_TEMPERATURE = 0.5
